# Generated by Django 2.2.4 on 2019-09-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_data/profile_picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='people',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='odm2admin.People'),
        ),
    ]
