# Generated by Django 2.2.4 on 2019-09-12 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190912_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='people',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='odm2admin.People'),
        ),
    ]
