# Generated by Django 2.2.4 on 2019-09-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190917_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_picture/avatar.png', null=True, upload_to='profile_picture'),
        ),
    ]
