# Generated by Django 2.2.4 on 2019-09-27 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190917_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='people',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='odm2admin.People'),
        ),
    ]
